#!/bin/bash

# Function to display information about a subdomain
display_info() {
    local subdomain=$1
    local domain=$2

    dig_output=$(dig $subdomain.$domain | awk '/^'${subdomain}'\.'${domain}'\./ {print $4, $5}')

    if [[ ! -z $dig_output ]]; then
        echo "The subdomain $subdomain is a $dig_output record and points to $(dig $subdomain.$domain +short)"
    fi
}

# Main function
main() {
    local domain=$1
    local subdomain=$2

    if [[ -z $subdomain ]]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=($subdomain)
    fi

    for sub in "${subdomains[@]}"; do
        display_info $sub $domain
    done
}

# Execute main function
main "$@"
