#!/usr/bin/env bash
# Gives info about my domain & subdomain

find_ip() {
    local domain="$1"
    local subdomain="$2"
    
    local ans=$(dig +short "$subdomain.$domain")
    local record_type=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION/{getline; print $4}')
    
    if [ -n "$ans" ]; then
        echo "The subdomain $subdomain is a $record_type record and points to $ans"
    else
        echo "No information found for subdomain $subdomain"
    fi
}

# Main function
main() {
    local domain="$1"
    
    # Default subdomains
    subdomains=("www" "lb-01" "web-01" "web-02")

    # If subdomain provided, use only that
    if [ "$#" -eq 2 ]; then
        find_ip "$domain" "$2"
    else
        for subdomain in "${subdomains[@]}"; do
            find_ip "$domain" "$subdomain"
        done
    fi
}

# Check arguments and call main function
if [ "$#" -eq 1 ] || [ "$#" -eq 2 ]; then
    main "$@"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi
