#!/usr/bin/env bash
# Gives info about my domain & subdomain

get_subdomain_info() {
    local domain="$1"
    local subdomain="$2"
    
    local record=$(dig +short "$subdomain.$domain" | head -1)
    local record_type=$(dig +short "$subdomain.$domain" | awk 'NR==1{print toupper($4)}')
    
    if [ -n "$record" ]; then
        echo "The subdomain $subdomain is a $record_type record and points to $record"
    fi
}

main() {
    local domain="$1"

    get_subdomain_info "$domain" "www"
    get_subdomain_info "$domain" "lb-01"
    get_subdomain_info "$domain" "web-01"
    get_subdomain_info "$domain" "web-02"
}

if [ "$#" -eq 1 ]; then
    main "$1"
elif [ "$#" -eq 2 ]; then
    get_subdomain_info "$1" "$2"
fi
