#!/usr/bin/env bash
#Nginx must be running, and listening on port 80
sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
