#!/usr/bin/env bash
#The script is content loops from 1 to 10 and displays different strings throughout specific iterations
x=1

while [ "$x" -lt 11 ]
do
    if [ "$x" -eq 4 ]
    then
        echo "bad luck"
    elif [ "$x" -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi

    ((x++))
done
